# Generated by Django 3.1.7 on 2021-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_picturebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturebase',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='picturebase',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, verbose_name='width'),
        ),
    ]
