# Generated by Django 3.1.7 on 2021-03-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210305_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
