# Generated by Django 3.1.7 on 2021-03-05 12:47

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('height', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='height')),
                ('width', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='width')),
                ('imagem', stdimage.models.StdImageField(upload_to='picturegoal', verbose_name='imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
