# Generated by Django 3.1.7 on 2021-03-06 19:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_picturegoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturegoal',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='picturebase', verbose_name='imagem'),
        ),
    ]
