# Generated by Django 3.1.7 on 2021-03-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210306_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturebase',
            name='goals',
            field=models.ManyToManyField(to='core.PictureGoal'),
        ),
    ]
