# Generated by Django 3.1.7 on 2021-03-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210307_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebase',
            name='height',
        ),
        migrations.RemoveField(
            model_name='gamebase',
            name='width',
        ),
    ]
