# Generated by Django 3.1.7 on 2021-03-07 15:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210307_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebase',
            name='imageAnswer',
            field=models.ImageField(blank=True, upload_to=core.models.upload_image_info),
        ),
    ]
