# Generated by Django 3.1.7 on 2021-03-08 03:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210307_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebase',
            name='action',
            field=models.CharField(choices=[('GRAYSCALE', 'grayscale')], default='GRAYSCALE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamebase',
            name='imageAnswer',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_info),
        ),
    ]
